### ISSUE TITLE
对RWKV的微调很感兴趣，可以交流一下吗~

### ISSUE THREAD

**Issue by KevinWang676** [Seikaijyu/RWKV-PEFT-Simple#2]
hi，我也是AI领域的开发者，做AI语音方向比较多，做过不少开源项目。同时，我也对于RWKV的微调很感兴趣，希望可以交流一下，看看有没有合作的机会~
我的邮箱是：talktalkai.kevin@gmail.com

**Comment by Seikaijyu** [comment]
可以加我Q互相交流：1959921673

**Comment by KevinWang676** [comment]
下午已经加过了哈哈
