### ISSUE TITLE
微调数据大小

### ISSUE THREAD

**Issue by shengxia** [Seikaijyu/RWKV-PEFT-Simple#3]
大佬，我想问一下一般要准备多少微调数据能达到效果呢？

**Comment by Seikaijyu** [comment]
具体看任务类型和模型参数量，如果模型参数量较小则需要更多的数据，如果底模型学习过类似的任务则可以降低数据量

**Comment by Seikaijyu** [comment]
对于我的任务来说，3B模型大约需要1200条数据才能充分学习

**Comment by Seikaijyu** [comment]
同时底模已经学习过类似任务，如果没学过，应该需要更多数据
